name: ientity
description: A starting point for Dart libraries or applications.
version: 0.0.9
homepage:
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'
  
dependencies:
  meta: any
    
  json_annotation_ex:
    git:
      url: https://github.com/TrueCollaboration/json_annotation_ex.dart.git
  json_ex:
    git:
      url: https://github.com/TrueCollaboration/json_ex.dart.git
    